[package]
name = "youkoso"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slint = "1.11"
tokio = { version = "1.45", features = ["full"] }
toml = "0.8"

[build-dependencies]
slint-build = "1.11"
