[package]
name = "youkoso"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
calamine = "0.27"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slint = "1.11"
thiserror = "2.0"
tokio = { version = "1.45", features = ["full"] }
toml = "0.8"

[build-dependencies]
slint-build = "1.11"

[patch.crates-io]
# TODO: Update calamine and remove the following when https://github.com/tafia/calamine/pull/506 gets merged
calamine = { git = "https://github.com/prophittcorey/calamine", branch = "fix/zip-3.0" }
